name: Provision Child Theme v2

on:
  workflow_dispatch:
    inputs:
      slug:
        description: "Site slug (kebab-case, used for theme folder)"
        required: true
      name:
        description: "Site display name"
        required: true
      brand:
        description: "Brand hex colour (e.g. #7A5A45)"
        required: true
      accent:
        description: "Accent hex colour (e.g. #D2B48C)"
        required: true
      hero:
        description: "Hero image URL"
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDWAYS_HOST: ${{ secrets.CLOUDWAYS_HOST }}
      CLOUDWAYS_USER: ${{ secrets.CLOUDWAYS_USER }}
      CLOUDWAYS_KEY:  ${{ secrets.CLOUDWAYS_SSH_KEY }}
      DEPLOY_PATH:    ${{ secrets.DEPLOY_PATH }}      # points at a theme path on the server
      APP_PATH:       ${{ secrets.APP_PATH }}         # /home/.../public_html
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH setup
        run: |
          set -eo pipefail
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printf '%s\n' "$CLOUDWAYS_KEY" > ~/.ssh/cloudways_id
          chmod 600 ~/.ssh/cloudways_id
          ssh-keyscan -H "$CLOUDWAYS_HOST" >> ~/.ssh/known_hosts

      - name: Generate child theme, build Tailwind v4, zip
        env:
          SLUG:  ${{ inputs.slug }}
          NAME:  ${{ inputs.name }}
          BRAND: ${{ inputs.brand }}
          ACCENT:${{ inputs.accent }}
          HERO:  ${{ inputs.hero }}
        run: |
          set -eo pipefail
          WORKDIR="$(mktemp -d)"; echo "Workdir: $WORKDIR"; cd "$WORKDIR"

          # scaffold
          mkdir -p child/assets/css child/assets/img child/dist
          cat > child/style.css <<CSS
          /*
          Theme Name: ${NAME} Child
          Template: sitefuse-agency
          Text Domain: ${SLUG}-child
          Version: 1.0.0
          */
          CSS
          cat > child/functions.php <<'PHP'
          <?php
          add_action('wp_enqueue_scripts', function () {
            $parent = get_template_directory_uri() . '/dist/tailwind.css';
            wp_enqueue_style('sitefuse-parent', $parent, [], null);
            $child_path = get_stylesheet_directory() . '/dist/tailwind.css';
            $ver = file_exists($child_path) ? filemtime($child_path) : null;
            wp_enqueue_style('sitefuse-child', get_stylesheet_directory_uri() . '/dist/tailwind.css', ['sitefuse-parent'], $ver);
          });
          PHP
          cat > child/assets/css/tailwind.css <<CSS
          @import "tailwindcss";
          /* design tokens */
          @theme {
            --font-sans: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Helvetica Neue, Arial;
            --color-brand: ${BRAND};
            --color-brand-600: color-mix(in oklab, ${BRAND} 85%, black);
            --color-accent: ${ACCENT};
            --color-cream: #FFF7EC;
          }
          .btn{ @apply inline-flex items-center justify-center rounded-lg px-5 py-2 font-semibold; }
          .btn-primary{ @apply btn bg-[--color-brand] text-white hover:bg-[--color-brand-600]; }
          .container{ @apply mx-auto max-w-6xl; }
          .card{ @apply bg-white rounded-xl shadow p-8 border border-slate-100; }
          .section-title{ @apply text-2xl md:text-3xl font-extrabold tracking-tight; }
          .lead{ @apply text-lg text-slate-700; }
          CSS

          cat > child/header.php <<'PHP'
          <!doctype html>
          <html <?php language_attributes(); ?>>
          <head>
            <meta charset="<?php bloginfo('charset'); ?>">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <?php wp_head(); ?>
          </head>
          <body <?php body_class('bg-[--color-cream] text-slate-900 font-sans'); ?>>
          <a class="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 p-2 bg-white rounded" href="#main">Skip to content</a>
          <header class="bg-white/90 backdrop-blur border-b">
            <div class="container px-4 py-4 flex items-center justify-between">
              <a class="text-xl font-extrabold tracking-tight text-[--color-brand]" href="<?php echo esc_url(home_url('/')); ?>"><?php bloginfo('name'); ?></a>
              <nav class="hidden md:block">
                <?php wp_nav_menu(['theme_location'=>'primary','menu_class'=>'md:flex md:items-center md:gap-6','container'=>false,'fallback_cb'=>'__return_empty_string']); ?>
              </nav>
            </div>
          </header>
          PHP

          cat > child/footer.php <<'PHP'
          <footer class="mt-16 bg-slate-900 text-slate-200">
            <div class="container px-4 py-10 grid gap-6 md:grid-cols-3">
              <div><div class="text-lg font-semibold">About</div><p class="text-sm opacity-80 mt-2">Neighbourhood coffee, fresh bakes, warm service.</p></div>
              <div><div class="text-lg font-semibold">Hours</div><ul class="text-sm opacity-80 mt-2 space-y-1"><li>Mon–Fri 7–3</li><li>Sat–Sun 8–2</li></ul></div>
              <div><div class="text-lg font-semibold">Find us</div><p class="text-sm opacity-80 mt-2">123 Lonsdale St, Canberra</p></div>
            </div>
            <div class="border-t border-slate-800"><div class="container px-4 py-4 text-sm opacity-70 flex justify-between"><span>© <?php echo date('Y'); ?> <?php bloginfo('name'); ?></span><span>Powered by WordPress</span></div></div>
          </footer>
          <?php wp_footer(); ?>
          </body>
          </html>
          PHP

          cat > child/front-page.php <<'PHP'
          <?php get_header(); ?>
          <main id="main" class="container px-4 py-10 space-y-12">
            <section class="relative overflow-hidden rounded-2xl bg-gradient-to-r from-[--color-brand] to-[--color-accent] text-white">
              <div class="px-6 py-16 md:px-12 md:py-24 grid md:grid-cols-2 gap-8 items-center">
                <div>
                  <h1 class="text-3xl md:text-5xl font-extrabold tracking-tight">Coffee, done properly</h1>
                  <p class="mt-4 lead text-white/90">Hand roasted beans, seasonal bakes and friendly faces in the heart of Canberra.</p>
                  <div class="mt-8 flex gap-4">
                    <a href="<?php echo esc_url(home_url('/menu')); ?>" class="btn-primary">View menu</a>
                    <a href="<?php echo esc_url(home_url('/contact')); ?>" class="btn ring-1 ring-inset ring-white/60 text-white">Book a table</a>
                  </div>
                </div>
                <div class="rounded-xl overflow-hidden shadow">
                  <img src="<?php echo esc_url( get_stylesheet_directory_uri() . '/assets/img/hero.jpg' ); ?>" alt="Fresh coffee" class="w-full h-full object-cover">
                </div>
              </div>
            </section>
            <section class="grid md:grid-cols-3 gap-6">
              <article class="card"><h3 class="font-bold text-lg">House blend</h3><p class="mt-2 text-sm text-slate-600">Balanced chocolate with a bright citrus finish.</p></article>
              <article class="card"><h3 class="font-bold text-lg">Daily bakes</h3><p class="mt-2 text-sm text-slate-600">Croissants, banana bread, seasonal tarts baked every morning.</p></article>
              <article class="card"><h3 class="font-bold text-lg">Local first</h3><p class="mt-2 text-sm text-slate-600">We source dairy, flour and produce from Canberra suppliers.</p></article>
            </section>
          </main>
          <?php get_footer(); ?>
          PHP

          # assets
          curl -fsSL "$HERO" -o child/assets/img/hero.jpg || true

          # Tailwind build (same as your green workflow)
          npx tailwindcss -i child/assets/css/tailwind.css -o child/dist/tailwind.css --minify

          # zip (also keep folder for rsync)
          (cd child && zip -qr "../${SLUG}-child.zip" .)
          ls -la

      - name: Deploy to Cloudways and activate
        env:
          SLUG: ${{ inputs.slug }}
        run: |
          set -eo pipefail
          test -n "$APP_PATH" || { echo "APP_PATH secret is required (e.g. /home/.../public_html)"; exit 1; }

          # Derive the remote themes dir from DEPLOY_PATH (which points at a theme)
          THEMES_DIR="$(ssh -i ~/.ssh/cloudways_id -o BatchMode=yes ${CLOUDWAYS_USER}@${CLOUDWAYS_HOST} "dirname '${DEPLOY_PATH}'")"

          # Upload (mirror) the child theme folder
          rsync -az --delete -e "ssh -i ~/.ssh/cloudways_id -o BatchMode=yes" \
            child/ "${CLOUDWAYS_USER}@${CLOUDWAYS_HOST}:${THEMES_DIR}/${SLUG}-child/"

          # Activate with WP-CLI
          ssh -i ~/.ssh/cloudways_id -o BatchMode=yes ${CLOUDWAYS_USER}@${CLOUDWAYS_HOST} "
            cd '${APP_PATH}' &&
            wp theme enable '${SLUG}-child' --quiet || true &&
            wp theme activate '${SLUG}-child' --quiet
          "
