name: Provision Child Theme
on:
  workflow_dispatch:
    inputs:
      slug:   { description: "Site slug", required: true }
      name:   { description: "Site display name", required: true }
      brand:  { description: "Brand hex colour", required: true }
      accent: { description: "Accent hex colour", required: true }
      hero:   { description: "Hero image URL", required: true }
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDWAYS_HOST: ${{ secrets.CLOUDWAYS_HOST }}
      CLOUDWAYS_USER: ${{ secrets.CLOUDWAYS_USER }}
      APP_PATH:       ${{ secrets.APP_PATH }}
    steps:
      - uses: actions/checkout@v4
      - name: SSH setup
        run: |
          set -e
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          printf "%s\n" "${{ secrets.CLOUDWAYS_SSH_KEY }}" > ~/.ssh/cloudways_id
          chmod 600 ~/.ssh/cloudways_id
          ssh-keyscan -H "$CLOUDWAYS_HOST" >> ~/.ssh/known_hosts
      - name: Generate child, build Tailwind v4, zip
        env:
          SLUG:  ${{ inputs.slug }}
          NAME:  ${{ inputs.name }}
          BRAND: ${{ inputs.brand }}
          ACCENT:${{ inputs.accent }}
          HERO:  ${{ inputs.hero }}
        run: |
          set -euo pipefail
          WORKDIR="$(mktemp -d)"; cd "$WORKDIR"
          mkdir -p child/assets/css child/assets/img child/dist
          cat <<CSS > child/style.css
          /*
          Theme Name: ${NAME} Child
          Template: sitefuse-agency
          Text Domain: ${SLUG}-child
          Version: 1.0.0
          */
          CSS
          cat <<'PHP' > child/functions.php
          <?php
          add_action('wp_enqueue_scripts', function () {
            $parent = get_template_directory_uri() . '/dist/tailwind.css';
            wp_enqueue_style('sitefuse-parent', $parent, [], null);
            $child_path = get_stylesheet_directory() . '/dist/tailwind.css';
            $ver = file_exists($child_path) ? filemtime($child_path) : null;
            wp_enqueue_style('sitefuse-child', get_stylesheet_directory_uri() . '/dist/tailwind.css', ['sitefuse-parent'], $ver);
          });
          PHP
          cat <<CSS > child/assets/css/tailwind.css
          @import "tailwindcss";
          @theme { --color-brand: ${BRAND}; --color-accent: ${ACCENT}; --color-cream: #FFF7EC; }
          .btn { @apply inline-flex items-center justify-center rounded-lg px-5 py-2 font-semibold; }
          .container { @apply mx-auto max-w-6xl; }
          .btn-primary { @apply btn bg-[--color-brand] text-white; }
          .card { @apply bg-white rounded-xl shadow p-8 border border-slate-100; }
          .section-title { @apply text-2xl md:text-3xl font-extrabold; }
          CSS
          cat <<'PHP' > child/header.php
          <!doctype html>
          <html <?php language_attributes(); ?>>
          <head>
            <meta charset="<?php bloginfo('charset'); ?>">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <?php wp_head(); ?>
          </head>
          <body <?php body_class('bg-[--color-cream] text-slate-900 font-sans'); ?>>
          <a class="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 p-2 bg-white rounded" href="#main">Skip to content</a>
          <header class="bg-white/90 backdrop-blur border-b">
            <div class="container px-4 py-4 flex items-center justify-between">
              <a class="text-xl font-extrabold tracking-tight text-[--color-brand]" href="<?php echo esc_url(home_url('/')); ?>"><?php bloginfo('name'); ?></a>
              <nav class="hidden md:block">
                <?php wp_nav_menu(['theme_location'=>'primary','menu_class'=>'md:flex md:items-center md:gap-6','container'=>false,'fallback_cb'=>'__return_empty_string','link_before'=>'<span class="nav-link">','link_after'=>'</span>']); ?>
              </nav>
            </div>
          </header>
          PHP
          cat <<'PHP' > child/footer.php
          <footer class="mt-16 bg-slate-900 text-slate-200">
            <div class="container px-4 py-10 grid gap-6 md:grid-cols-3">
              <div><div class="text-lg font-semibold">About</div><p class="text-sm opacity-80 mt-2">Neighbourhood coffee, fresh bakes, warm service.</p></div>
              <div><div class="text-lg font-semibold">Hours</div><ul class="text-sm opacity-80 mt-2 space-y-1"><li>Mon to Fri 7am to 3pm</li><li>Sat to Sun 8am to 2pm</li></ul></div>
              <div><div class="text-lg font-semibold">Find us</div><p class="text-sm opacity-80 mt-2">123 Lonsdale Street, Canberra</p></div>
            </div>
            <div class="border-t border-slate-800"><div class="container px-4 py-4 text-sm opacity-70 flex justify-between"><span>© <?php echo date('Y'); ?> <?php bloginfo('name'); ?></span><span>Powered by WordPress</span></div></div>
          </footer>
          <?php wp_footer(); ?>
          </body>
          </html>
          PHP
          cat <<'PHP' > child/front-page.php
          <?php get_header(); ?>
          <main id="main" class="container px-4 py-10 space-y-12">
            <section class="relative overflow-hidden rounded-2xl bg-gradient-to-r from-[--color-brand] to-[--color-accent] text-white">
              <div class="px-6 py-16 md:px-12 md:py-24 grid md:grid-cols-2 gap-8 items-center">
                <div>
                  <h1 class="text-3xl md:text-5xl font-extrabold tracking-tight">Coffee, done properly</h1>
                  <p class="mt-4 text-white/90">Hand roasted beans, seasonal bakes and friendly faces in the heart of Canberra.</p>
                  <div class="mt-8 flex gap-4">
                    <a href="<?php echo esc_url(home_url('/menu')); ?>" class="btn-primary">View menu</a>
                    <a href="<?php echo esc_url(home_url('/contact')); ?>" class="btn ring-1 ring-inset ring-white/60 text-white">Book a table</a>
                  </div>
                </div>
                <div class="rounded-xl overflow-hidden shadow">
                  <img src="<?php echo esc_url( get_stylesheet_directory_uri() . '/assets/img/hero.jpg' ); ?>" alt="Fresh coffee" class="w-full h-full object-cover">
                </div>
              </div>
            </section>
            <section class="grid md:grid-cols-3 gap-6">
              <article class="card"><h3 class="font-bold text-lg">House blend</h3><p class="mt-2 text-sm text-slate-600">Balanced chocolate notes with a bright citrus finish.</p></article>
              <article class="card"><h3 class="font-bold text-lg">Daily bakes</h3><p class="mt-2 text-sm text-slate-600">Croissants, banana bread, seasonal tarts baked every morning.</p></article>
              <article class="card"><h3 class="font-bold text-lg">Local first</h3><p class="mt-2 text-sm text-slate-600">We source dairy, flour and produce from Canberra suppliers.</p></article>
            </section>
          </main>
          <?php get_footer(); ?>
          PHP
          curl -fsSL "$HERO" -o child/assets/img/hero.jpg || true
          npm_config_userconfig=/dev/null npx --yes --package tailwindcss@4 tailwindcss -- -i child/assets/css/tailwind.css -o child/dist/tailwind.css --minify
          (cd child && zip -qr "../${SLUG}-child.zip" .)
          mv "${SLUG}-child.zip" "$GITHUB_WORKSPACE/"
      - name: Deploy child theme and activate
        run: |
          set -e
          CHILD="${{ inputs.slug }}-child"
          WP_ROOT="$(dirname "$(dirname "$APP_PATH")")"
          rsync -avz -e "ssh -i ~/.ssh/cloudways_id" --delete "${{ inputs.slug }}-child.zip" "${CLOUDWAYS_USER}@${CLOUDWAYS_HOST}:${WP_ROOT}/"
          ssh -i ~/.ssh/cloudways_id "${CLOUDWAYS_USER}@${CLOUDWAYS_HOST}" bash -lc "
            set -e
            cd '$WP_ROOT/wp-content/themes'
            rm -rf '$CHILD'
            mkdir -p '$CHILD'
            cd '$WP_ROOT'
            unzip -oq '${{ inputs.slug }}-child.zip' -d 'wp-content/themes/${CHILD}'
            rm -f '${{ inputs.slug }}-child.zip'
            cd '$WP_ROOT'
            wp theme activate '${CHILD}' || wp theme install 'wp-content/themes/${CHILD}' --activate
          "
